// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3OLll2HT0F2-sQPBBaaklgRIZQgCQz3E',
    appId: '1:70495693955:web:8f1cedda357196c303bfb6',
    messagingSenderId: '70495693955',
    projectId: 'firebase-hang-example',
    authDomain: 'fir-hang-example.firebaseapp.com',
    storageBucket: 'firebase-hang-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3LaV8NkTxmZN25O-Xlcpytq3RFaQlbY0',
    appId: '1:70495693955:android:d2d53e109b5fc8cc03bfb6',
    messagingSenderId: '70495693955',
    projectId: 'firebase-hang-example',
    storageBucket: 'firebase-hang-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrjt_wTVHrRqDaysuWIFrxEhJT3Orj1dU',
    appId: '1:70495693955:ios:2c85cb5529b1973403bfb6',
    messagingSenderId: '70495693955',
    projectId: 'firebase-hang-example',
    storageBucket: 'firebase-hang-example.appspot.com',
    iosClientId: '70495693955-nvf4me2j6vhit1ut4o7icgmhkt6lhd18.apps.googleusercontent.com',
    iosBundleId: 'com.hangexample.firebaseHangExample',
  );
}
